import { BookOpenText, CalendarDays, ChevronLeft, Heart, Megaphone, Music, Plus, ShieldCheck, Trash2, UserRound } from 'lucide-react-native';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { AppText as Text, AppTextInput as TextInput } from '../components/AppText';
import { Icon } from '../components/Icon';
import { MediaPicker } from '../components/MediaPicker';
import { useAuth } from '../context/AuthContext';
import { createAdminContent, deleteAdminContent, getAdminContent, getAdminOracoes, getAdminUsuarioOracoes, getAdminUsers, updateAdminContent, updateAdminUserRole } from '../services/api';
import { colors } from '../theme/colors';
import { radius, spacing, typography } from '../theme/tokens';
import { AdminContentKind, AdminUser, Oracao } from '../types';

type AdminSection = 'home' | 'prayers' | 'users' | AdminContentKind;
type Field = { key: string; label: string; multiline?: boolean; image?: boolean };
type ContentConfig = { title: string; icon: typeof Heart; id: string; name: string; fields: Field[] };

const contentConfigs: Record<AdminContentKind, ContentConfig> = {
  ministerios: { title: 'Ministérios', icon: Heart, id: 'ministerio_id', name: 'nome_ministerio', fields: [{ key: 'nome_ministerio', label: 'Nome' }, { key: 'descricao_ministerio', label: 'Descrição', multiline: true }, { key: 'url_ministerio', label: 'Link' }, { key: 'imagem_url', label: 'Imagem', image: true }] },
  eventos: { title: 'Eventos', icon: CalendarDays, id: 'evento_id', name: 'nome_evento', fields: [{ key: 'nome_evento', label: 'Nome' }, { key: 'descricao_evento', label: 'Descrição', multiline: true }, { key: 'data_evento', label: 'Data (ISO)' }, { key: 'endereco_evento', label: 'Endereço' }, { key: 'imagem_url', label: 'Capa', image: true }] },
  noticias: { title: 'Notícias', icon: Megaphone, id: 'noticia_id', name: 'nome_noticia', fields: [{ key: 'nome_noticia', label: 'Título' }, { key: 'mensagem_noticia', label: 'Conteúdo', multiline: true }, { key: 'data_noticia', label: 'Data (ISO)' }, { key: 'observacao_noticia', label: 'Observação' }, { key: 'imagem_url', label: 'Imagem', image: true }] },
  mensagens: { title: 'Mensagens', icon: BookOpenText, id: 'mensagem_id', name: 'nome_mensagem', fields: [{ key: 'nome_mensagem', label: 'Título' }, { key: 'texto_mensagem', label: 'Mensagem', multiline: true }] },
  louvores: { title: 'Louvores', icon: Music, id: 'louvor_id', name: 'nome_louvor', fields: [{ key: 'nome_louvor', label: 'Nome' }, { key: 'url_louvor', label: 'Link' }, { key: 'observacao_louvor', label: 'Observação', multiline: true }] },
};

export const AdminScreen = () => {
  const { user } = useAuth();
  const [section, setSection] = useState<AdminSection>('home');
  if (user?.role !== 'admin') return <View style={styles.center}><Icon as={ShieldCheck} size={30} /><Text style={styles.title}>Acesso restrito</Text><Text style={styles.subtitle}>Esta área está disponível somente para administradores.</Text></View>;
  if (section === 'prayers') return <AdminPrayers onBack={() => setSection('home')} />;
  if (section === 'users') return <AdminUsers currentUserId={user.usuario_id} onBack={() => setSection('home')} />;
  if (section !== 'home') return <AdminContent kind={section} onBack={() => setSection('home')} />;
  const entries: Array<{ key: AdminSection; title: string; icon: typeof Heart }> = [
    { key: 'prayers', title: 'Orações', icon: Heart }, { key: 'users', title: 'Usuários', icon: UserRound },
    ...Object.entries(contentConfigs).map(([key, config]) => ({ key: key as AdminContentKind, title: config.title, icon: config.icon })),
  ];
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.kicker}>Controle de acesso</Text><Text style={styles.title}>Administração</Text><Text style={styles.subtitle}>Gerencie pessoas e conteúdos públicos do aplicativo.</Text><View style={styles.grid}>{entries.map(entry => <Pressable key={entry.key} style={styles.hubCard} onPress={() => setSection(entry.key)}><Icon as={entry.icon} size={22} /><Text style={styles.hubText}>{entry.title}</Text></Pressable>)}</View></ScrollView>;
};

const AdminPrayers = ({ onBack }: { onBack: () => void }) => {
  const [items, setItems] = useState<Oracao[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState<'all' | 'prayed' | 'pending'>('all'); const [error, setError] = useState('');
  const load = useCallback(async (next = 1) => { setLoading(true); setError(''); try { const result = await getAdminOracoes(next, 20); setItems(result.items); setPage(result.pagination.page); setPages(result.pagination.totalPages); } catch { setError('Não foi possível carregar os pedidos.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = items.filter(item => filter === 'all' || (filter === 'prayed' ? item.orado_por_mim : !item.orado_por_mim));
  return <AdminLayout title="Orações" onBack={onBack}>{<View style={styles.filters}>{(['all', 'prayed', 'pending'] as const).map(value => <Pressable key={value} style={[styles.filter, filter === value && styles.filterActive]} onPress={() => setFilter(value)}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{value === 'all' ? 'Todos' : value === 'prayed' ? 'Já orei' : 'Ainda não orei'}</Text></Pressable>)}</View>}{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{visible.map(item => <View key={item.oracao_id} style={styles.card}><Text style={styles.itemTitle}>{item.nome_pedido}</Text><Text style={styles.itemMeta}>{item.orado_por_mim ? 'Você já orou' : 'Você ainda não orou'} · {item.total_oracoes ?? 0} pessoa(s)</Text><Text style={styles.itemBody}>{item.descricao_pedido}</Text></View>)}<Pager page={page} pages={pages} disabled={loading} onPage={load} /></AdminLayout>;
};

const AdminUsers = ({ currentUserId, onBack }: { currentUserId: string; onBack: () => void }) => {
  const [items, setItems] = useState<AdminUser[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const [prayerUser, setPrayerUser] = useState<AdminUser | null>(null); const [userPrayers, setUserPrayers] = useState<Oracao[]>([]); const [loadingPrayers, setLoadingPrayers] = useState(false);
  const load = useCallback(async (next = 1, term = search) => { setLoading(true); setError(''); try { const result = await getAdminUsers(next, 20, term); setItems(result.items); setPage(result.pagination.page); setPages(result.pagination.totalPages); } catch { setError('Não foi possível carregar os usuários.'); } finally { setLoading(false); } }, [search]);
  useEffect(() => { load(1, ''); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const changeRole = (item: AdminUser) => { const role = item.role === 'admin' ? 'user' : 'admin'; Alert.alert('Alterar papel', `${item.nome_usuario} será ${role}.`, [{ text: 'Cancelar', style: 'cancel' }, { text: 'Confirmar', onPress: async () => { try { const updated = await updateAdminUserRole(item.usuario_id, role); setItems(current => current.map(value => value.usuario_id === updated.usuario_id ? updated : value)); } catch { Alert.alert('Não foi possível alterar', 'Tente novamente.'); } } }]); };
  const showPrayers = async (item: AdminUser) => { setPrayerUser(item); setLoadingPrayers(true); try { const result = await getAdminUsuarioOracoes(item.usuario_id, 1, 100); setUserPrayers(result.items); } catch { setUserPrayers([]); Alert.alert('Não foi possível carregar', 'Tente novamente.'); } finally { setLoadingPrayers(false); } };
  return <AdminLayout title="Usuários" onBack={onBack}><View style={styles.searchRow}><TextInput value={search} onChangeText={setSearch} onSubmitEditing={() => load(1)} placeholder="Buscar usuário" placeholderTextColor={colors.textSecondary} style={styles.input} /><Pressable style={styles.searchButton} onPress={() => load(1)}><Text style={styles.searchButtonText}>Buscar</Text></Pressable></View>{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{items.map(item => <View key={item.usuario_id} style={styles.card}><Text style={styles.itemTitle}>{item.nome_usuario}</Text><Text style={styles.itemMeta}>{item.email_usuario} · {item.role}</Text><View style={styles.inlineActions}><Pressable style={styles.roleButton} onPress={() => showPrayers(item)}><Text style={styles.roleText}>Ver orações</Text></Pressable><Pressable disabled={item.usuario_id === currentUserId} style={[styles.roleButton, item.usuario_id === currentUserId && styles.disabled]} onPress={() => changeRole(item)}><Text style={styles.roleText}>{item.usuario_id === currentUserId ? 'Sua própria conta' : item.role === 'admin' ? 'Tornar usuário' : 'Tornar admin'}</Text></Pressable></View></View>)}<Pager page={page} pages={pages} disabled={loading} onPage={load} /><Modal visible={Boolean(prayerUser)} transparent animationType="slide" onRequestClose={() => setPrayerUser(null)}><View style={styles.modalLayer}><Pressable style={styles.backdrop} onPress={() => setPrayerUser(null)} /><ScrollView style={styles.editor} contentContainerStyle={styles.editorContent}><Text style={styles.editorTitle}>Orações de {prayerUser?.nome_usuario}</Text>{loadingPrayers ? <ActivityIndicator color={colors.primary} /> : userPrayers.map(item => <View key={item.oracao_id} style={styles.card}><Text style={styles.itemTitle}>{item.nome_pedido}</Text><Text style={styles.itemMeta}>{item.orado_por_mim ? 'Orou' : 'Ainda não orou'}</Text></View>)}{!loadingPrayers && !userPrayers.length ? <Text style={styles.subtitle}>Nenhum pedido encontrado.</Text> : null}<Pressable style={styles.cancelButton} onPress={() => setPrayerUser(null)}><Text style={styles.cancelText}>Fechar</Text></Pressable></ScrollView></View></Modal></AdminLayout>;
};

const AdminContent = ({ kind, onBack }: { kind: AdminContentKind; onBack: () => void }) => {
  const config = contentConfigs[kind]; const [items, setItems] = useState<Record<string, unknown>[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<Record<string, unknown> | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (next = 1) => { setLoading(true); setError(''); try { const result = await getAdminContent<Record<string, unknown>>(kind, next, 20); setItems(result.items); setPage(result.pagination.page); setPages(result.pagination.totalPages); } catch { setError(`Não foi possível carregar ${config.title.toLowerCase()}.`); } finally { setLoading(false); } }, [config.title, kind]);
  useEffect(() => { load(); }, [load]);
  const remove = (item: Record<string, unknown>) => Alert.alert('Excluir conteúdo', 'Esta ação não pode ser desfeita.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await deleteAdminContent(kind, String(item[config.id])); await load(page); } catch { Alert.alert('Não foi possível excluir', 'Tente novamente.'); } } }]);
  return <AdminLayout title={config.title} onBack={onBack}><Pressable style={styles.addButton} onPress={() => { setEditing(null); setOpen(true); }}><Icon as={Plus} size={18} color={colors.white} /><Text style={styles.addText}>Novo</Text></Pressable>{loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{items.map(item => <Pressable key={String(item[config.id])} style={styles.card} onPress={() => { setEditing(item); setOpen(true); }}><Text style={styles.itemTitle}>{String(item[config.name] ?? 'Sem título')}</Text><View style={styles.deleteRow}><Text style={styles.itemMeta}>Toque para editar</Text><Pressable accessibilityLabel="Excluir" style={styles.deleteButton} onPress={() => remove(item)}><Icon as={Trash2} size={18} /></Pressable></View></Pressable>)}<Pager page={page} pages={pages} disabled={loading} onPage={load} /><ContentEditor visible={open} kind={kind} config={config} item={editing} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(page); }} /></AdminLayout>;
};

const ContentEditor = ({ visible, kind, config, item, onClose, onSaved }: { visible: boolean; kind: AdminContentKind; config: ContentConfig; item: Record<string, unknown> | null; onClose: () => void; onSaved: () => void }) => {
  const initial = useMemo(() => Object.fromEntries(config.fields.map(field => [field.key, String(item?.[field.key] ?? '')])), [config.fields, item]); const [form, setForm] = useState<Record<string, string>>(initial); const [saving, setSaving] = useState(false);
  useEffect(() => { if (visible) setForm(initial); }, [initial, visible]);
  const save = async () => { const first = config.fields.find(field => !field.image); if (!first || !form[first.key]?.trim()) { Alert.alert('Campo obrigatório', `Preencha ${first?.label ?? 'os dados'}.`); return; } setSaving(true); try { const payload = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value.trim() || null])); if (item) await updateAdminContent(kind, String(item[config.id]), payload); else await createAdminContent(kind, payload); onSaved(); } catch { Alert.alert('Não foi possível salvar', 'Revise os dados e tente novamente.'); } finally { setSaving(false); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalLayer}><Pressable style={styles.backdrop} onPress={onClose} /><ScrollView style={styles.editor} contentContainerStyle={styles.editorContent}><Text style={styles.editorTitle}>{item ? 'Editar' : 'Novo'} {config.title.toLowerCase()}</Text>{config.fields.map(field => field.image ? <MediaPicker key={field.key} context={kind} value={form[field.key]} onChange={value => setForm(current => ({ ...current, [field.key]: value }))} /> : <View key={field.key}><Text style={styles.label}>{field.label}</Text><TextInput value={form[field.key]} onChangeText={value => setForm(current => ({ ...current, [field.key]: value }))} multiline={field.multiline} textAlignVertical={field.multiline ? 'top' : 'center'} style={[styles.input, field.multiline && styles.textArea]} /></View>)}<View style={styles.editorActions}><Pressable style={styles.cancelButton} onPress={onClose}><Text style={styles.cancelText}>Cancelar</Text></Pressable><Pressable disabled={saving} style={styles.saveButton} onPress={save}>{saving ? <ActivityIndicator color={colors.white} /> : <Text style={styles.saveText}>Salvar</Text>}</Pressable></View></ScrollView></View></Modal>;
};

const AdminLayout = ({ title, onBack, children }: React.PropsWithChildren<{ title: string; onBack: () => void }>) => <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.adminHeader}><Pressable accessibilityLabel="Voltar" style={styles.backButton} onPress={onBack}><Icon as={ChevronLeft} /></Pressable><Text style={styles.headerTitle}>{title}</Text><View style={styles.backPlaceholder} /></View>{children}</ScrollView>;
const Pager = ({ page, pages, disabled, onPage }: { page: number; pages: number; disabled: boolean; onPage: (page: number) => void }) => pages <= 1 ? null : <View style={styles.pager}><Pressable disabled={page <= 1 || disabled} style={styles.pageButton} onPress={() => onPage(page - 1)}><Icon as={ChevronLeft} /></Pressable><Text style={styles.itemMeta}>{page} de {pages}</Text><Pressable disabled={page >= pages || disabled} style={styles.pageButton} onPress={() => onPage(page + 1)}><Icon as={ChevronLeft} style={styles.nextIcon} /></Pressable></View>;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.page, paddingBottom: 44 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.page, backgroundColor: colors.background }, kicker: { color: colors.textSecondary, fontSize: typography.caption, fontWeight: '600' }, title: { color: colors.textPrimary, fontSize: typography.title, fontWeight: '600', marginTop: 4 }, subtitle: { color: colors.textSecondary, lineHeight: 21, marginTop: 6 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: spacing.section }, hubCard: { width: '48%', minHeight: 94, justifyContent: 'space-between', padding: spacing.md, borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, backgroundColor: colors.surface }, hubText: { color: colors.textPrimary, fontWeight: '600' },
  adminHeader: { minHeight: 52, flexDirection: 'row', alignItems: 'center', marginBottom: spacing.section }, backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, backPlaceholder: { width: 44 }, headerTitle: { flex: 1, color: colors.textPrimary, fontSize: typography.heading, fontWeight: '600', textAlign: 'center' }, filters: { flexDirection: 'row', gap: 6, marginBottom: 14 }, filter: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, filterActive: { backgroundColor: colors.primary }, filterText: { color: colors.textSecondary, fontSize: typography.caption, fontWeight: '600' }, filterTextActive: { color: colors.white }, error: { color: colors.danger, paddingVertical: 14 }, card: { padding: spacing.md, marginBottom: 10, borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, backgroundColor: colors.surface }, itemTitle: { color: colors.textPrimary, fontSize: typography.subtitle, fontWeight: '600' }, itemMeta: { color: colors.textSecondary, fontSize: typography.caption, marginTop: 5 }, itemBody: { color: colors.textSecondary, lineHeight: 21, marginTop: 10 }, roleButton: { alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center', marginTop: 8, paddingHorizontal: 12, borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, roleText: { color: colors.textPrimary, fontWeight: '600' }, disabled: { opacity: 0.5 }, inlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, searchRow: { flexDirection: 'row', gap: 8, marginBottom: 14 }, input: { flex: 1, minHeight: 46, paddingHorizontal: 12, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.inputBackground, marginBottom: 10 }, searchButton: { minHeight: 46, justifyContent: 'center', paddingHorizontal: 14, borderRadius: radius.md, backgroundColor: colors.primary }, searchButtonText: { color: colors.white, fontWeight: '600' }, addButton: { minHeight: 44, flexDirection: 'row', alignSelf: 'flex-end', alignItems: 'center', gap: 8, paddingHorizontal: 14, marginBottom: 12, borderRadius: radius.md, backgroundColor: colors.primary }, addText: { color: colors.white, fontWeight: '600' }, deleteRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, deleteButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, pager: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 14, marginTop: 10 }, pageButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, nextIcon: { transform: [{ rotate: '180deg' }] },
  modalLayer: { flex: 1, justifyContent: 'flex-end' }, backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.48)' }, editor: { maxHeight: '90%', borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: colors.surface }, editorContent: { padding: spacing.page, paddingBottom: 32 }, editorTitle: { color: colors.textPrimary, fontSize: typography.heading, fontWeight: '600', marginBottom: 16 }, label: { color: colors.textPrimary, fontWeight: '600', marginBottom: 7 }, textArea: { minHeight: 120, paddingTop: 12 }, editorActions: { flexDirection: 'row', gap: 10, marginTop: 6 }, cancelButton: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: colors.textSecondary, fontWeight: '600' }, saveButton: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary }, saveText: { color: colors.white, fontWeight: '600' },
});
